### ISSUE TITLE
This factory class only works with shared library

### ISSUE THREAD

**Issue by Phymin** [Derydoca/factory-auto-registration#1]
Hi, I found your repository from your blog, and it's really an awesome implementaion of factory pattern. But from my test, if I change the foodfactory project to a static library, the UI factory won't work, and there is no registered class in the foodfactory, Could you tell me why this happens and is it possible to use static library? Thanks.

**Comment by Derydoca** [comment]
Hi Phymin! I'm glad my repository was helpful for you. The problem you are seeing with using a static library has to do with the linker only including any class that has a hard reference in your application. This factory pattern references the types within it very loosely and only with string references which the linker cannot predict what classes to include in the final executable. There is a way to use this pattern while also using a static library.
You will have to use the `/WHOLEARCHIVE` linker option to force the linker to include every class type in your library. That option is what the Microsoft C++ linker uses and I don't know what the equivalent for other compilers would be, but it should exist. [Here is the MSDN article on the option.](https://docs.microsoft.com/en-us/cpp/build/reference/wholearchive-include-all-library-object-files?view=vs-2019) If you do want to use a static library, my suggestion would be to have a separate project for the classes or structs to be constructed by the factory and use the '/WHOLEARCHIVE' on only that project. That way the linker can be smart about all other classes in your project and strip out code you are not using.
I hope this makes sense. Let me know if I can clarify a specific area further.

**Comment by Phymin** [comment]
Hello, I didn't expect you reply so soon, thanks a lot. Actually I finally also find that I should link the static library with /WHOLEARCHIVE. But they think this is not a good choice(but I think I will try you suggestion). And I use linux system with CMake to manage the build, and I don't find a standard way to link this option in CMake.

**Comment by Derydoca** [comment]
I see. I ended up finding a link about a discussion for CMake that sounds like the very same use-case of wanting to use /WHOLEARCHIVE in CMake for an auto-registering factory and they mentioned that not all compilers support this function so CMake does not have this as an option. Alternatively, you can manually specify the /WHOLEARCHIVE command for cases when you are compiling with Microsoft's compiler, but that would partially defeat the benefit of using CMake. They did mention that CMake 'object libraries' is what should be used in this particular use-case, but I am not familiar with them or how they work. [Here is the link to the thread](https://gitlab.kitware.com/cmake/cmake/-/issues/16947). I hope that helps you!

**Comment by Phymin** [comment]
Hi Derydoca! Really thanks for your kindly reply. I will give it a try.
